site_name: Experiment Control with Python Course

theme:
  name: material
  logo: figures/ECPC_logo_plain.svg
  favicon: figures/ECPC_logo_simple.svg
  features:
    - content.code.copy
    - toc.integrate
    - navigation.top
    - content.code.annotate 

plugins:
  - search
  - bibtex:
      bib_file: "docs/referenties.bib"
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - def_list
  - tables
  - toc:
      permalink: true

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - javascripts/model.js
  - assets/comparison/comparison.js
  - assets/ADC_slider/ADC_slider.js
  - assets/run_button/run_button.js
  - assets/cheatsheets/cheatsheets.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css
  - assets/folder_tree/folder_tree.css
  - assets/comparison/comparison.css
  - assets/ADC_slider/ADC_slider.css
  - assets/run_button/run_button.css
  - assets/cheatsheets/cheatsheets.css
  - assets/particle-spin-flip/spin-flip.css

nav:
  - index.md
  - Voorkennis:
    - basis-python.md
    - vervolg-python.md
  - communicatie.md
  - github.md
  - basisscript.md
  - classes.md
  - mvc.md
  - docstrings.md
  - poetry.md
  - cli.md
  - gui.md
  - eindfeest.md
  - Appendices:
      - software-tools.md
      - cheatsheets.md
      - firmware.md
      - kleurcodes.md
      - diodes.md
      - terminal-adventure-game.md
      - zonnecel.md
      

extra:
    arrow_rotate: ':fontawesome-solid-arrow-rotate-right:'
    branch: ':fontawesome-solid-code-branch:'
    copy: ':material-content-copy:'
    dots: '&bull;&bull;&bull;'
    enter: '<svg class="enter" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path d="M21 10.5c0 4.14-3.36 7.5-7.5 7.5H11v4l-7-6l7-6v4h2.5c1.93 0 3.5-1.57 3.5-3.5V3h4z"/></svg>'
    feesttoeter: ':material-party-popper:'
    file: ':fontawesome-regular-file-code:'
    file_lines: ':fontawesome-regular-file-lines:'
    folder: ':fontawesome-regular-folder:'
    github: ':fontawesome-brands-github:'
    L: '└──'
    lightbulb: ':fontawesome-regular-lightbulb:'
    new_file: '<span style="color: green;">:fontawesome-regular-file-code:</span>'
    new_file_lines: '<span style="color: green;">:fontawesome-regular-file-lines:</span>'
    new_folder: '<span style="color: green;">:fontawesome-regular-folder:</span>'
    reload: '<svg class="reload" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M386.3 160H336c-17.7 0-32 14.3-32 32s14.3 32 32 32H464c17.7 0 32-14.3 32-32V64c0-17.7-14.3-32-32-32s-32 14.3-32 32v51.2L414.4 97.6c-87.5-87.5-229.3-87.5-316.8 0s-87.5 229.3 0 316.8s229.3 87.5 316.8 0c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0c-62.5 62.5-163.8 62.5-226.3 0s-62.5-163.8 0-226.3s163.8-62.5 226.3 0L386.3 160z"/></svg>'
    run: '<svg class="run" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>'
    star: ':material-star:'
    T: '├──'
    tab: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
    trash: ':fontawesome-regular-trash-can:'
