[project]
name = "ecpc"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-bibtex>=4.4.0",
    "mkdocs-macros-plugin>=1.3.7",
    "mkdocs-material>=9.6.16",
]

[tool.poe.tasks]
serve = "mkdocs serve"
deploy = "mkdocs gh-deploy"
